FROM maven:latest as maven
WORKDIR /app
COPY ./src src
COPY pom.xml .
RUN mvn clean package -DskipTests

FROM openjdk:8-jdk-alpine
 
WORKDIR /app
COPY --from=maven /app/target/*.jar /app/app.jar

ENV DOCKER_PORT=$DOCKER_PORT
EXPOSE ${DOCKER_PORT}

CMD ["java", "-jar", "app.jar", "--spring.profiles.active=dev", "--spring.config.location=classpath:application-docker.properties", "--management.server.port=${DOCKER_PORT}","--server.port=${DOCKER_PORT}"]